
ğŸ“Š metrics embed:
  - changed-files:
    - any-glob-to-any-file:
      - source/app/action/**
      - source/app/web/**

âœ¨ metrics insights:
  - changed-files:
    - any-glob-to-any-file:
      - source/app/web/statics/insights/**

ğŸ§© plugins:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/**

ğŸ–¼ï¸ templates:
  - changed-files:
    - any-glob-to-any-file:
      - source/templates/**

ğŸ—ƒï¸ base:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/base/**

ğŸ§± core:
  - changed-files:
    - any-glob-to-any-file:
      - source/app/metrics/**
      - source/plugins/core/**

ğŸš€ ci:
  - changed-files:
    - any-glob-to-any-file:
      - .github/**

âš™ï¸ ci config:
  - changed-files:
    - any-glob-to-any-file:
      - .github/config/**
      - .github/ISSUE_TEMPLATE/**
      - .github/FUNDING.yml
      - .github/pull_request_template.md

ğŸ¦¾ ci actions:
  - changed-files:
    - any-glob-to-any-file:
      - .github/actions/**

ğŸ¦¿ ci scripts:
  - changed-files:
    - any-glob-to-any-file:
      - .github/scripts/**

ğŸ–¨ï¸ ci docs:
  - changed-files:
    - any-glob-to-any-file:
      - .github/readme/**
      - .github/**/examples.yml
      - .github/**/*.md
      - '!.github/pull_request_template.md'
      - .github/architecture.svg
      - .github/scripts/markdown_example.mjs
      - .github/scripts/presets_example.mjs

ğŸ² community plugins:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/community/**

ğŸ† plugin achievements:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/achievements/**
ğŸ“° plugin activity:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/activity/**

ğŸŒ¸ plugin anilist:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/anilist/**

ğŸ“† plugin calendar:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/calendar/**

â™ plugin code:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/code/**

ğŸ… plugin contributors:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/contributors/**

ğŸ’¬ plugin discussions:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/discussions/**

ğŸŸï¸ plugin followup:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/followup/**

ğŸ« plugin gists:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/gists/**

ğŸ’¡ plugin habits:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/habits/**

ğŸ™‹ plugin introduction:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/introduction/**

ğŸ“… plugin isocalendar:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/isocalendar/**

ğŸˆ·ï¸ plugin languages:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/languages/**

ğŸ—³ï¸ plugin leetcode:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/leetcode/**

ğŸ“œ plugin licenses:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/licenses/**

ğŸ‘¨â€ğŸ’» plugin lines:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/lines/**

ğŸ¼ plugin music:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/music/**

ğŸ© plugin notable:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/notable/**

â±ï¸ plugin pagespeed:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/pagespeed/**

ğŸ§‘â€ğŸ¤â€ğŸ§‘ plugin people:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/people/**

âœ’ï¸ plugin posts:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/posts/**

ğŸ—‚ï¸ plugin projects:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/projects/**

ğŸ­ plugin reactions:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/reactions/**

ğŸ““ plugin repositories:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/repositories/**

ğŸ—¼ plugin rss:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/rss/**

ğŸŒ‡ plugin skyline:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/skyline/**

ğŸ’• plugin sponsors:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/sponsors/**

ğŸ—¨ï¸ plugin stackoverflow:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/stackoverflow/**

âœ¨ plugin stargazers:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/stargazers/**

ğŸ’« plugin starlists:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/starlists/**

ğŸŒŸ plugin stars:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/stars/**

ğŸ’­ plugin support:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/support/**

ğŸ“Œ plugin topics:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/topics/**

ğŸ§® plugin traffic:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/traffic/**

ğŸ¤ plugin tweets:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/tweets/**

â° plugin wakatime:
  - changed-files:
    - any-glob-to-any-file:
      - source/plugins/wakatime/**

